--- #YAML:1.0
name:               MojoX-Renderer-JSON
version:            0.11
abstract:           JSON renderer for Mojo
author:
    - Graham Barr <gbarr@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
requires:
    JSON:        2.10
    Test::More:  0
resources:
    repository:  http://git.goingon.net/?p=MojoX-Renderer-JSON.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.48
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
