---
abstract: 'Fast L<JSON::XS> rendering handler for L<Mojolicious::Renderer>'
author:
  - 'yowcow <yowcow@cpan.org>'
build_requires:
  Test::More: 0.98
configure_requires:
  CPAN::Meta: 0
  CPAN::Meta::Prereqs: 0
  Module::Build: 0.38
dynamic_config: 0
generated_by: 'Minilla/v0.7.0, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MojoX-Renderer-JSON
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
    - author
provides:
  MojoX::Renderer::JSON:
    file: lib/MojoX/Renderer/JSON.pm
    version: 0.02
  Mojolicious::Plugin::JsonRenderer:
    file: lib/Mojolicious/Plugin/JsonRenderer.pm
    version: 0
requires:
  JSON::XS: 0
  Mojolicious: 0
  perl: 5.008005
resources:
  bugtracker: https://github.com/yowcow/MojoX-Renderer-JSON/issues
  homepage: https://github.com/yowcow/MojoX-Renderer-JSON
  repository: git://github.com/yowcow/MojoX-Renderer-JSON.git
version: 0.02
